development:
  adapter: postgresql
  encoding: unicode
  database: whattodo_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: whattodo_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: whattodo_production
  host: localhost
  pool: 5
  username:
  password:
